### PR TITLE
Add pure DOM support and CI test setup

### PR DESCRIPTION
**Pull request by lijunle**
Hi, @kevindente 

I have implemented the pure DOM support, add unit test and set up CI test.

Besides, the following modifications:
1. Remove jQuery dependency from implementation
2. Add git ignore file for node project
3. Check in jQuery to branch for testing
4. Update expect.js to the newest version (0.3.1)
5. Update README examples
6. Remove `handle` and `handleWith` assertions, which are meaningless
7. Promote the package version to 0.0.2

**Note**

The CI test result is pointing to my [Travis CI result](https://travis-ci.org/lijunle/expect-dom) and [Sauce Labs result](https://saucelabs.com/u/lijunle_expect-dom). You can update it after merge.

Please review the changes.

### CODE REVIEW

**Comment by lijunle** [comment]
Hi, @kevindente 

Because you does not reply to this RP. I decided to create a [new package](https://www.npmjs.com/package/expect-dom.js) in NPM and continuously maintain the project.

If you think that is not good, please touch me.

Thanks!
Junle

**Comment by kevindente** [comment]
Sorry I've been busy with some family stuff. I'll try to merge your pr today.

**Comment by lijunle** [comment]
@kevindente sorry, I have renamed the project to this:
https://github.com/lijunle/expect-dom.js

I have made some additional changes from the latest commit in the RP. You can diff them offline.

**Comment by lijunle** [comment]
Hi, @kevindente . Any update?

**Comment by kevindente** [comment]
Sorry, you closed the pull request, so I wasn't clear if you still wanted me to merge it, or if you just wanted to maintain yours as an independent project.

**Comment by kevindente** [comment]
OK, the changes have been merged and pushed to npm. Thanks for your help, and sorry it took so long. I bumped the version to 1.0.0 to start being more semver-y

**Comment by lijunle** [comment]
Basically, I do not want to separate the project and maintain a fork.

It could be great that add me as a collaborator. I have some ideas relating to the project, adding some new APIs. I will start a new issue to discuss that.

**Comment by lijunle** [comment]
Besides, I don't think pump up version to 1.0.0 is a good idea. There are still some issues before bring it to production.

**Comment by kevindente** [comment]
OK, I finally added you as a collaborator.

What kind of issues? I've used it on my own project for a while, and it doesn't have an big bugs that I'm aware of.

**Pull request closed without merging**
